/**
 * This class is generated by jOOQ
 */
package com.yumcouver.spoonie.database;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>yumcouver</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<com.yumcouver.spoonie.database.tables.records.DocumentRecord> KEY_DOCUMENT_PRIMARY = UniqueKeys0.KEY_DOCUMENT_PRIMARY;
	public static final org.jooq.UniqueKey<com.yumcouver.spoonie.database.tables.records.YumDictionaryRecord> KEY_YUM_DICTIONARY_PRIMARY = UniqueKeys0.KEY_YUM_DICTIONARY_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<com.yumcouver.spoonie.database.tables.records.DocumentRecord> KEY_DOCUMENT_PRIMARY = createUniqueKey(com.yumcouver.spoonie.database.tables.Document.DOCUMENT, com.yumcouver.spoonie.database.tables.Document.DOCUMENT.URL);
		public static final org.jooq.UniqueKey<com.yumcouver.spoonie.database.tables.records.YumDictionaryRecord> KEY_YUM_DICTIONARY_PRIMARY = createUniqueKey(com.yumcouver.spoonie.database.tables.YumDictionary.YUM_DICTIONARY, com.yumcouver.spoonie.database.tables.YumDictionary.YUM_DICTIONARY.WORD);
	}
}
