/**
 * This class is generated by jOOQ
 */
package com.yumcouver.spoonie.database;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in yumcouver
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table yumcouver.DOCUMENT
	 */
	public static final com.yumcouver.spoonie.database.tables.Document DOCUMENT = com.yumcouver.spoonie.database.tables.Document.DOCUMENT;

	/**
	 * The table yumcouver.yum_dictionary
	 */
	public static final com.yumcouver.spoonie.database.tables.YumDictionary YUM_DICTIONARY = com.yumcouver.spoonie.database.tables.YumDictionary.YUM_DICTIONARY;
}
