/**
 * This class is generated by jOOQ
 */
package com.yumcouver.spoonie.database;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Yumcouver extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -1208646069;

	/**
	 * The singleton instance of <code>yumcouver</code>
	 */
	public static final Yumcouver YUMCOUVER = new Yumcouver();

	/**
	 * No further instances allowed
	 */
	private Yumcouver() {
		super("yumcouver");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			com.yumcouver.spoonie.database.tables.Document.DOCUMENT,
			com.yumcouver.spoonie.database.tables.YumDictionary.YUM_DICTIONARY);
	}
}
