/**
 * This class is generated by jOOQ
 */
package com.yumcouver.spoonie.database.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DocumentRecord extends org.jooq.impl.UpdatableRecordImpl<com.yumcouver.spoonie.database.tables.records.DocumentRecord> implements org.jooq.Record2<java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 1663282910;

	/**
	 * Setter for <code>yumcouver.DOCUMENT.URL</code>.
	 */
	public void setUrl(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>yumcouver.DOCUMENT.URL</code>.
	 */
	public java.lang.String getUrl() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>yumcouver.DOCUMENT.CONTENT</code>.
	 */
	public void setContent(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>yumcouver.DOCUMENT.CONTENT</code>.
	 */
	public java.lang.String getContent() {
		return (java.lang.String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return com.yumcouver.spoonie.database.tables.Document.DOCUMENT.URL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.yumcouver.spoonie.database.tables.Document.DOCUMENT.CONTENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getUrl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getContent();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DocumentRecord value1(java.lang.String value) {
		setUrl(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DocumentRecord value2(java.lang.String value) {
		setContent(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DocumentRecord values(java.lang.String value1, java.lang.String value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DocumentRecord
	 */
	public DocumentRecord() {
		super(com.yumcouver.spoonie.database.tables.Document.DOCUMENT);
	}

	/**
	 * Create a detached, initialised DocumentRecord
	 */
	public DocumentRecord(java.lang.String url, java.lang.String content) {
		super(com.yumcouver.spoonie.database.tables.Document.DOCUMENT);

		setValue(0, url);
		setValue(1, content);
	}
}
