/**
 * This class is generated by jOOQ
 */
package com.yumcouver.spoonie.database.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class YumDictionaryRecord extends org.jooq.impl.UpdatableRecordImpl<com.yumcouver.spoonie.database.tables.records.YumDictionaryRecord> implements org.jooq.Record1<java.lang.String> {

	private static final long serialVersionUID = 790547229;

	/**
	 * Setter for <code>yumcouver.yum_dictionary.word</code>.
	 */
	public void setWord(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>yumcouver.yum_dictionary.word</code>.
	 */
	public java.lang.String getWord() {
		return (java.lang.String) getValue(0);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record1 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row1<java.lang.String> fieldsRow() {
		return (org.jooq.Row1) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row1<java.lang.String> valuesRow() {
		return (org.jooq.Row1) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return com.yumcouver.spoonie.database.tables.YumDictionary.YUM_DICTIONARY.WORD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getWord();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public YumDictionaryRecord value1(java.lang.String value) {
		setWord(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public YumDictionaryRecord values(java.lang.String value1) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached YumDictionaryRecord
	 */
	public YumDictionaryRecord() {
		super(com.yumcouver.spoonie.database.tables.YumDictionary.YUM_DICTIONARY);
	}

	/**
	 * Create a detached, initialised YumDictionaryRecord
	 */
	public YumDictionaryRecord(java.lang.String word) {
		super(com.yumcouver.spoonie.database.tables.YumDictionary.YUM_DICTIONARY);

		setValue(0, word);
	}
}
