/**
 * This class is generated by jOOQ
 */
package com.yumcouver.spoonie.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Document extends org.jooq.impl.TableImpl<com.yumcouver.spoonie.database.tables.records.DocumentRecord> {

	private static final long serialVersionUID = 1527854518;

	/**
	 * The singleton instance of <code>yumcouver.DOCUMENT</code>
	 */
	public static final com.yumcouver.spoonie.database.tables.Document DOCUMENT = new com.yumcouver.spoonie.database.tables.Document();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.yumcouver.spoonie.database.tables.records.DocumentRecord> getRecordType() {
		return com.yumcouver.spoonie.database.tables.records.DocumentRecord.class;
	}

	/**
	 * The column <code>yumcouver.DOCUMENT.URL</code>.
	 */
	public final org.jooq.TableField<com.yumcouver.spoonie.database.tables.records.DocumentRecord, java.lang.String> URL = createField("URL", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>yumcouver.DOCUMENT.CONTENT</code>.
	 */
	public final org.jooq.TableField<com.yumcouver.spoonie.database.tables.records.DocumentRecord, java.lang.String> CONTENT = createField("CONTENT", org.jooq.impl.SQLDataType.CLOB.length(65535).nullable(false), this, "");

	/**
	 * Create a <code>yumcouver.DOCUMENT</code> table reference
	 */
	public Document() {
		this("DOCUMENT", null);
	}

	/**
	 * Create an aliased <code>yumcouver.DOCUMENT</code> table reference
	 */
	public Document(java.lang.String alias) {
		this(alias, com.yumcouver.spoonie.database.tables.Document.DOCUMENT);
	}

	private Document(java.lang.String alias, org.jooq.Table<com.yumcouver.spoonie.database.tables.records.DocumentRecord> aliased) {
		this(alias, aliased, null);
	}

	private Document(java.lang.String alias, org.jooq.Table<com.yumcouver.spoonie.database.tables.records.DocumentRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.yumcouver.spoonie.database.Yumcouver.YUMCOUVER, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.yumcouver.spoonie.database.tables.records.DocumentRecord> getPrimaryKey() {
		return com.yumcouver.spoonie.database.Keys.KEY_DOCUMENT_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.yumcouver.spoonie.database.tables.records.DocumentRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.yumcouver.spoonie.database.tables.records.DocumentRecord>>asList(com.yumcouver.spoonie.database.Keys.KEY_DOCUMENT_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.yumcouver.spoonie.database.tables.Document as(java.lang.String alias) {
		return new com.yumcouver.spoonie.database.tables.Document(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.yumcouver.spoonie.database.tables.Document rename(java.lang.String name) {
		return new com.yumcouver.spoonie.database.tables.Document(name, null);
	}
}
