/**
 * This class is generated by jOOQ
 */
package com.yumcouver.spoonie.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class YumDictionary extends org.jooq.impl.TableImpl<com.yumcouver.spoonie.database.tables.records.YumDictionaryRecord> {

	private static final long serialVersionUID = -1121155901;

	/**
	 * The singleton instance of <code>yumcouver.yum_dictionary</code>
	 */
	public static final com.yumcouver.spoonie.database.tables.YumDictionary YUM_DICTIONARY = new com.yumcouver.spoonie.database.tables.YumDictionary();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.yumcouver.spoonie.database.tables.records.YumDictionaryRecord> getRecordType() {
		return com.yumcouver.spoonie.database.tables.records.YumDictionaryRecord.class;
	}

	/**
	 * The column <code>yumcouver.yum_dictionary.word</code>.
	 */
	public final org.jooq.TableField<com.yumcouver.spoonie.database.tables.records.YumDictionaryRecord, java.lang.String> WORD = createField("word", org.jooq.impl.SQLDataType.VARCHAR.length(40).nullable(false), this, "");

	/**
	 * Create a <code>yumcouver.yum_dictionary</code> table reference
	 */
	public YumDictionary() {
		this("yum_dictionary", null);
	}

	/**
	 * Create an aliased <code>yumcouver.yum_dictionary</code> table reference
	 */
	public YumDictionary(java.lang.String alias) {
		this(alias, com.yumcouver.spoonie.database.tables.YumDictionary.YUM_DICTIONARY);
	}

	private YumDictionary(java.lang.String alias, org.jooq.Table<com.yumcouver.spoonie.database.tables.records.YumDictionaryRecord> aliased) {
		this(alias, aliased, null);
	}

	private YumDictionary(java.lang.String alias, org.jooq.Table<com.yumcouver.spoonie.database.tables.records.YumDictionaryRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.yumcouver.spoonie.database.Yumcouver.YUMCOUVER, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.yumcouver.spoonie.database.tables.records.YumDictionaryRecord> getPrimaryKey() {
		return com.yumcouver.spoonie.database.Keys.KEY_YUM_DICTIONARY_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.yumcouver.spoonie.database.tables.records.YumDictionaryRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.yumcouver.spoonie.database.tables.records.YumDictionaryRecord>>asList(com.yumcouver.spoonie.database.Keys.KEY_YUM_DICTIONARY_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.yumcouver.spoonie.database.tables.YumDictionary as(java.lang.String alias) {
		return new com.yumcouver.spoonie.database.tables.YumDictionary(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.yumcouver.spoonie.database.tables.YumDictionary rename(java.lang.String name) {
		return new com.yumcouver.spoonie.database.tables.YumDictionary(name, null);
	}
}
